name: 编译mipsel-xfrpc

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:
env:
  TZ: Asia/Shanghai
jobs:
 check:
  runs-on: ubuntu-latest
  outputs:
    ver: ${{ steps.getversion.outputs.ver }}
    cver: ${{ steps.getversion.outputs.cver }}
  steps:
  - name: 检查更新
    id: getversion
    run: |
      ver=`curl https://api.github.com/repos/liudf0716/xfrpc/releases/latest | jq -r '.tag_name'`
      cver=`curl https://api.github.com/repos/lmq8267/xfrpc-mipsel/releases/latest | jq -r '.tag_name'`
      echo "ver=${ver}" >> $GITHUB_OUTPUT
      echo "cver=${cver}" >> $GITHUB_OUTPUT
 build:
    runs-on: ubuntu-latest
    needs: check
    if: ${{ needs.check.outputs.ver != needs.check.outputs.cver }}
    steps:
      - uses: actions/checkout@v3
      - name: 下载工具链
        run: |
          git clone https://github.com/liudf0716/xfrpc /opt/xfrpc
          wget -c https://github.com/lmq8267/vnt-cli/releases/download/Armada370-ToolChain/buildroot-2023.02.5-mipsel-uclibc.zip -P /opt/gcc/
          unzip /opt/gcc/buildroot-2023.02.5-mipsel-uclibc.zip -d /opt/gcc/
          sudo chmod 777 -R /opt/gcc
          sudo timedatectl set-timezone "Asia/Shanghai"
      - 
        name: 编译xfrpc
        shell: bash
        run: |
          cd /opt/xfrpc
          export PATH=$PATH:/opt/gcc/host/bin
          export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/opt/gcc/host/lib
          mipsel-linux-gcc -v
          mkdir build && cd build
          cmake -DTHIRDPARTY_STATIC_BUILD=mips -DCMAKE_C_COMPILER=mipsel-linux-gcc -D THIRDPARTY_STATIC_BUILD=ON ..
          make
      - 
        name: 剥离压缩
        run: |
          mkdir -p /opt/xfrpc_mipsel/upx
          git clone https://github.com/lmq8267/cloudflared.git /opt/st
          tar -xvf /opt/st/upx-3.95-amd64_linux.tar.xz -C /opt
          chmod 777 /opt/upx-3.95-amd64_linux/upx
          cd /opt/xfrpc/build
          file xfrpc
          cp -rf /opt/xfrpc/build/xfrpc /opt/xfrpc_mipsel/xfrpc
          cp -rf /opt/xfrpc/build/xfrpc /opt/xfrpc_mipsel/upx/xfrpc
          
          cd /opt/xfrpc_mipsel/upx
          /opt/gcc/host/bin/mipsel-linux-strip xfrpc
          /opt/upx-3.95-amd64_linux/upx --lzma --best xfrpc
          cd /opt
          zip -r xfrpc_mipsel.zip xfrpc_mipsel
          echo "build_time=$(date '+%Y-%m-%d %H:%M:%S')" >> $GITHUB_ENV
      - name : 上传
        uses: actions/upload-artifact@master
        if: always()
        with:
         name: xfrpc_mipsel
         path: /opt/xfrpc_mipsel.zip
      - name: 发布
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.c8 }}
          body: |
           > ### 编译时间 ：${{ env.build_time }}

           [官方更新说明](https://github.com/liudf0716/xfrpc/releases)

          tag_name: ${{ needs.check.outputs.ver }}
          files: |
              /opt/xfrpc_mipsel/upx/xfrpc
              /opt/xfrpc_mipsel.zip
      -       
       name: 删除工作流
       uses: GitRML/delete-workflow-runs@main
       with:
        token: ${{ secrets.c8 }}
        retain_days: 2
        keep_minimum_runs: 0
